version: '3'

# Define the output binary name (optional)
vars:
  BINARY_NAME: cards

tasks:
  clean:
    cmds:
      - rm -rf {{.BINARY_NAME}} || true  # Clean up the built binary (ignore errors)

  build:
    # Ensure clean runs before build
    deps: [ clean ]
    cmds:
      - go build -o {{.BINARY_NAME}} .  # Build the program

  run:
    # Ensure build runs before run
    deps: [ build ]
    cmds:
      - ./{{.BINARY_NAME}}  # Run the program
